services:
  postgres:
    # Thay đổi image từ postgres:15 sang pgvector/pgvector:pg15
    image: pgvector/pgvector:pg15
    container_name: nestjs_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
